---
server:
  port: 8001
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/thiagolrc/spring-cloud
          searchPaths: configData
management:
  endpoints:
    web:
      exposure:
        include: "*"