---
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/

---
#Example of how to configure multiple profile sections
spring:
  profiles: production
eureka:
  client:
    serviceUrl:
      defaultZone: http://eurekasever/eureka/w